In [3]:
from sklearn import datasets

In [4]:
import matplotlib.pyplot as plt
x_index = 3
color = ['blue','red','green']
for label,color in zip(range(len(iris.target_names)), color):
    plt.hist(iris.data[iris.target==label,x_index], label=iris.target_names[label],color=color)

plt.xlabel(iris.feature_names[x_index])
plt.legend(loc="upper right")
plt.show()

NameError: name 'iris' is not defined

In [18]:
x_index=0
y_index=1
colors=['blue','red','green']
for label,color in zip(range(len(iris.target_names)),colors):
    plt.scatter(iris.data[iris.target==label,x_index],
                iris.data[iris.target==label,y_index],
                label=iris.target_names[label],
                c=color)
plt.xlabel(iris.feature_names[x_index])
plt.ylabel(iris.feature_names[y_index])
plt.legend(loc='upper left')
plt.show()

In [2]:
iris = datasets.load_iris()
iris.data.shape

(150, 4)

In [3]:
print(iris.data)
print(iris.feature_names)
print(iris.target)
print(iris.target_names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
import pandas as pd

In [5]:
data = iris.data
feature_names = iris.feature_names
target = iris.target
target_names = iris.target_names

data_with_feature = {feature_names[0] : data[:,0],feature_names[1] : data[:,1],feature_names[2] : data[:,2], "target":target}
    
data_with_feature = pd.DataFrame(data_with_feature)

data_with_feature['PetalLengthCm'] = data_with_feature['petal length (cm)']
data_with_feature['SepalLengthCm'] = data_with_feature['sepal length (cm)']
data_with_feature['SepalWidthCm'] = data_with_feature['sepal width (cm)']
data_with_feature.drop(['petal length (cm)','sepal length (cm)', 'sepal width (cm)'],axis=1,inplace=True)
data_with_feature.drop('target',axis=1,inplace=True)
data_with_feature.insert(3,'Target',target)
data_with_feature

PetalLengthCm  SepalLengthCm  SepalWidthCm  Target
0              1.4            5.1           3.5       0
1              1.4            4.9           3.0       0
2              1.3            4.7           3.2       0
3              1.5            4.6           3.1       0
4              1.4            5.0           3.6       0
5              1.7            5.4           3.9       0
6              1.4            4.6           3.4       0
7              1.5            5.0           3.4       0
8              1.4            4.4           2.9       0
9              1.5            4.9           3.1       0
10             1.5            5.4           3.7       0
11             1.6            4.8           3.4       0
12             1.4            4.8           3.0       0
13             1.1            4.3           3.0       0
14             1.2            5.8           4.0       0
15             1.5            5.7           4.4       0
16             1.3            5.4           3.9       0
17             1.4            5.1           3.5       0
18             1.7            5.7           3.8       0
19             1.5            5.1           3.8       0
20             1.7            5.4           3.4       0
21             1.5            5.1           3.7       0
22             1.0            4.6           3.6       0
23             1.7            5.1           3.3       0
24             1.9            4.8           3.4       0
25             1.6            5.0           3.0       0
26             1.6            5.0           3.4       0
27             1.5            5.2           3.5       0
28             1.4            5.2           3.4       0
29             1.6            4.7           3.2       0
..             ...            ...           ...     ...
120            5.7            6.9           3.2       2
121            4.9            5.6           2.8       2
122            6.7            7.7           2.8       2
123            4.9            6.3           2.7       2
124            5.7            6.7           3.3       2
125            6.0            7.2           3.2       2
126            4.8            6.2           2.8       2
127            4.9            6.1           3.0       2
128            5.6            6.4           2.8       2
129            5.8            7.2           3.0       2
130            6.1            7.4           2.8       2
131            6.4            7.9           3.8       2
132            5.6            6.4           2.8       2
133            5.1            6.3           2.8       2
134            5.6            6.1           2.6       2
135            6.1            7.7           3.0       2
136            5.6            6.3           3.4       2
137            5.5            6.4           3.1       2
138            4.8            6.0           3.0       2
139            5.4            6.9           3.1       2
140            5.6            6.7           3.1       2
141            5.1            6.9           3.1       2
142            5.1            5.8           2.7       2
143            5.9            6.8           3.2       2
144            5.7            6.7           3.3       2
145            5.2            6.7           3.0       2
146            5.0            6.3           2.5       2
147            5.2            6.5           3.0       2
148            5.4            6.2           3.4       2
149            5.1            5.9           3.0       2

[150 rows x 4 columns]

In [6]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()

from sklearn.model_selection import train_test_split
trainSet, testSet = train_test_split(data_with_feature, test_size=0.33)
print(trainSet.shape)
print(testSet.shape)
print(trainSet.head(3))

(100, 4)
(50, 4)
     PetalLengthCm  SepalLengthCm  SepalWidthCm  Target
102            5.9            7.1           3.0       2
128            5.6            6.4           2.8       2
7              1.5            5.0           3.4       0


In [7]:
trainData = pd.DataFrame.as_matrix(trainSet[['PetalLengthCm','SepalLengthCm','SepalWidthCm']])
trainTarget = pd.DataFrame.as_matrix(trainSet[['Target']]).ravel() #change vector to series
testData = pd.DataFrame.as_matrix(testSet[['PetalLengthCm','SepalLengthCm','SepalWidthCm']])
testTarget = pd.DataFrame.as_matrix(testSet[['Target']]).ravel()

In [8]:
clf.fit(trainData, trainTarget)
y_pred = clf.predict(testData)
ground_truth = testTarget
print(y_pred)
print(ground_truth)

[0 2 1 1 2 1 2 1 0 1 1 0 2 1 2 0 1 0 1 0 2 0 1 1 0 0 1 0 0 2 2 1 1 0 1 0 2
 1 2 2 2 2 2 1 0 2 2 1 0 1]
[0 1 1 1 1 1 1 2 0 1 1 0 2 2 2 0 1 0 1 0 2 0 2 1 0 0 1 0 0 2 2 1 2 0 1 0 2
 1 2 2 2 2 2 1 0 2 2 1 0 2]


In [9]:
import numpy as np
correct_prediction = np.equal(y_pred,ground_truth).sum()
accuracy = correct_prediction/len(testData)
print("Accuracy is:", accuracy)

Accuracy is: 0.84


In [10]:
from sklearn import svm
clf = svm.SVC(gamma=0.001,C=100.)
clf.fit(trainData, trainTarget)
y_pred = clf.predict(testData)
ground_truth = testTarget
print(y_pred)
print(ground_truth)
correct_prediction = np.equal(y_pred,ground_truth).sum()
accuracy = correct_prediction/len(testData)
print("Accuracy is:", accuracy)

[0 1 1 1 2 1 1 1 0 1 1 0 2 1 2 0 1 0 1 0 2 0 2 1 0 0 1 0 0 2 2 1 1 0 1 0 2
 1 2 2 2 2 2 1 0 2 2 1 0 2]
[0 1 1 1 1 1 1 2 0 1 1 0 2 2 2 0 1 0 1 0 2 0 2 1 0 0 1 0 0 2 2 1 2 0 1 0 2
 1 2 2 2 2 2 1 0 2 2 1 0 2]
Accuracy is: 0.92
